import { useApi } from './useApi';
import { reportApi } from '../services/reportApi';
import type { CitizenReport } from '../types';

const fallbackReports: CitizenReport[] = [
  {
    id: 'rpt-001',
    category: 'landslide',
    severity: 'Critical',
    description: 'Active debris flow observed near NH-13 Km 54, blocking one lane. Soil and rocks on road surface.',
    latitude: 27.534,
    longitude: 92.122,
    locationName: 'Sela Pass Approach',
    state: 'Arunachal Pradesh',
    reporterName: 'Capt. R. Singh (BRO)',
    status: 'VERIFIED',
    photoUrls: [],
    videoUrls: [],
    photoCount: 3,
    videoCount: 1,
    timestamp: '2026-08-24T14:22:00',
    dataSource: { source: 'DEMO', lastUpdated: new Date().toISOString() },
  },
  {
    id: 'rpt-002',
    category: 'crack_observed',
    severity: 'High',
    description: 'Tension cracks noticed on hillside slope above railway track near Jatinga station.',
    latitude: 25.132,
    longitude: 93.034,
    locationName: 'Jatinga Lampu Ridge',
    state: 'Assam',
    reporterName: 'Field Engineer M. Bora',
    status: 'UNDER_REVIEW',
    photoUrls: [],
    videoUrls: [],
    photoCount: 5,
    videoCount: 0,
    timestamp: '2026-08-24T11:45:00',
    dataSource: { source: 'DEMO', lastUpdated: new Date().toISOString() },
  },
  {
    id: 'rpt-003',
    category: 'water_seepage',
    severity: 'Moderate',
    description: 'Heavy water seepage from cut slope on NH-40 near Umiam. Road surface is wet and slippery.',
    latitude: 25.654,
    longitude: 91.892,
    locationName: 'Umiam Cut Section',
    state: 'Meghalaya',
    reporterName: 'PWD Inspector K. Lyngdoh',
    status: 'ACTIONED',
    photoUrls: [],
    videoUrls: [],
    photoCount: 2,
    videoCount: 0,
    timestamp: '2026-08-24T09:10:00',
    dataSource: { source: 'DEMO', lastUpdated: new Date().toISOString() },
  },
  {
    id: 'rpt-004',
    category: 'road_blockage',
    severity: 'Critical',
    description: 'Complete road blockage due to debris at Noney corridor. No vehicular movement possible.',
    latitude: 24.795,
    longitude: 93.598,
    locationName: 'Noney Corridor',
    state: 'Manipur',
    reporterName: 'SDRF Team Lead',
    status: 'NEW',
    photoUrls: [],
    videoUrls: [],
    photoCount: 4,
    videoCount: 2,
    timestamp: '2026-08-24T07:30:00',
    dataSource: { source: 'DEMO', lastUpdated: new Date().toISOString() },
  },
  {
    id: 'rpt-005',
    category: 'subsidence',
    severity: 'High',
    description: 'Road subsidence observed near Gangtok bypass road. Width of settlement approx 2m.',
    latitude: 27.338,
    longitude: 88.606,
    locationName: 'Gangtok Bypass Corridor',
    state: 'Sikkim',
    reporterName: 'District Engineer P. Tamang',
    status: 'RESOLVED',
    photoUrls: [],
    videoUrls: [],
    photoCount: 2,
    videoCount: 0,
    timestamp: '2026-08-23T16:00:00',
    dataSource: { source: 'DEMO', lastUpdated: new Date().toISOString() },
  },
];

export function useReports(params?: { status?: string; category?: string }) {
  return useApi<CitizenReport[]>(
    () => reportApi.getAll(params),
    fallbackReports,
    [params?.status, params?.category]
  );
}
